spring.application.name=StoreApis
order.version=/v1/
products.version=/v1/
payment.version=/v1/
client.version=/v1/
token.secretKey=x7O+5lmP8N7PP8b/hQ8O0LMVxRJ0RZm/R89Z0WRR5ITXZK8O21PmsTjlrS+7j5zmt4TZYZZHId2kUDGH0rJXRA==

spring.datasource.url=jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.springframework.orm.jpa=ERROR

# CircuitBreaker para paymentService
resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10s

# Retry para paymentService
resilience4j.retry.instances.globalService.maxAttempts=3
resilience4j.retry.instances.globalService.waitDuration=2s

